Repository github/libprojfs, pull requests merged in 2019-02, with the labels that each got.

#25 introduce projfs_get_user_data() public API method
  include/projfs.h
  lib/projfs.c
  lib/projfs_vfsapi.c
Labels: api

#26 mark test exit_usage() as noreturn
  t/test_common.c
Labels: testing

#29 use public projfs API only in VFS code
  lib/projfs_vfsapi.c
Labels: vfs

#31 simplify VFS and other mirror tests
  t/Makefile.am
  t/README.md
  t/t004-mirror-stat.t
  t/t005-mirror-links.t
  t/t006-mirror-statfs.t
  t/t007-mirror-attrs.t
  t/t500-vfs-mirror-basic.t
  t/t500-vfs-mirror-read.t
  t/t500/f2.txt
  t/t500/ls.d1
  t/t500/ls.d2
  t/t500/ls.target
  t/t500/nf1.txt
  t/t500/sort.source
  t/t501-vfs-mirror-mkdir.t
  t/t501/sort.source
  t/t501/sort.target
  t/t502-vfs-mirror-write.t
  t/t502/f2.txt
  t/t503-vfs-mirror-remove.t
  t/t503/sort.source
  t/t503/sort.target
Labels: testing

#37 CI status badge and minor build doc edits
  README.md
  docs/build-install.md
Labels: documentation

#36 enhance CI suite logging, mount path configs, and cleanup
  docker/cibuild
  docker/projfs
  t/Makefile.am
  t/clean_test_dirs.sh
  t/test-lib.sh
Labels: testing

#38 revise and refine test lib common vars and error exits
  t/test_common.c
  t/wait_mount.c
Labels: testing

#39 add projection test handlers to test suite
  t/t200-event-ok.t
  t/t201-event-err.t
  t/t202-event-deny.t
  t/t203-event-null.t
  t/t204-event-allow.t
  t/t700-vfs-event-ok.t
  t/t701-vfs-event-err.t
  t/t702-vfs-event-deny.t
  t/t703-vfs-event-null.t
  t/t704-vfs-event-allow.t
  t/test_common.c
  t/test_common.h
  t/test_projfs_handlers.c
  t/test_vfsapi_handlers.c
Labels: projection, testing

#40 File projection
  include/projfs_vfsapi.h
  lib/projfs.c
  lib/projfs_vfsapi.c
Labels: projection

#43 check lower fs for xattr and sparse file support
  lib/projfs.c
Labels: suggestion

#50 report src+dst and add tests for rename events
  include/projfs_notify.h
  lib/projfs.c
  lib/projfs_vfsapi.c
  t/t200-event-ok.t
  t/t201-event-err.t
  t/t202-event-deny.t
  t/t203-event-null.t
  t/t204-event-allow.t
  t/t700-vfs-event-ok.t
  t/t701-vfs-event-err.t
  t/t702-vfs-event-deny.t
  t/t703-vfs-event-null.t
  t/t704-vfs-event-allow.t
  t/test-lib-event.sh
  t/test_projfs_handlers.c
  t/test_vfsapi_handlers.c
Labels: api, testing, vfs

#46 File/dir rename events
  include/projfs_notify.h
  lib/projfs.c
  lib/projfs_vfsapi.c
  t/t200-event-ok.t
  t/t201-event-err.t
  t/t202-event-deny.t
  t/t203-event-null.t
  t/t204-event-allow.t
  t/t700-vfs-event-ok.t
  t/t701-vfs-event-err.t
  t/t702-vfs-event-deny.t
  t/t703-vfs-event-null.t
  t/t704-vfs-event-allow.t
  t/test-lib-event.sh
  t/test_projfs_handlers.c
  t/test_vfsapi_handlers.c
Labels: api, vfs

#52 add vfs test callback for file hydration
  t/test_projfs_handlers.c
  t/test_vfsapi_handlers.c
Labels: projection, testing, vfs

#51 test that we actually lock dirs on projection
  t/Makefile.am
  t/t203-event-null.t
  t/t205-event-locking.t
  t/test-lib-functions.sh
  t/test_common.c
  t/test_common.h
  t/test_projfs_handlers.c
Labels: projection, testing
